<?php

namespace AppBundle\Repository;

/**
 * dataloginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class dataloginRepository extends \Doctrine\ORM\EntityRepository
{
}
